### ISSUE TITLE
Consider moving cloud run service to example

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/terraform-google-log-analysis#14]
Is Cloud Run a part of the solution or more for demonstration. Based on a quick glance, it seems the latter in which case, we should be it to an example and to showcase the functionality of the blueprint.

**Comment by ryotat7** [comment]
Yes, Cloud Run is used to demonstrate actual web access logs that are being exported to BigQuery. So the Cloud Run piece could be moved to an example.

**Comment by ryotat7** [comment]
Moved the Cloud Run to an example
