### ISSUE TITLE
Modules should not contain provider initialization

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/terraform-google-log-analysis#3]
Provider initialization should be done by the calling root module. We can remove https://github.com/GoogleCloudPlatform/terraform-google-log-analysis/blob/2dc9c004c779c4c744cd8a8276b812ac620e1aca/main.tf#L17-L20. Project should be passed in at the resource level.

**Comment by ryotat7** [comment]
Removed provider from main.tf
