### ISSUE TITLE
enable uniform-bucket-level access

### ISSUE THREAD

**Issue by eeaton** [GoogleCloudPlatform/terraform-google-log-analysis#36]
Configuring Uniform Bucket Level Access is a standard security recommendation when configuring a GCS bucket, otherwise object-level ACLs can easily be exfiltrated to non-org members.
https://cloud.google.com/storage/docs/using-uniform-bucket-level-access

UBLA is also enforced by many google recommended frameworks such as the Security Foundations Blueprint, so trying to deploy this repo in an environment configured to Google recommended best practices without enabling UBLA will fail.
https://cloud.google.com/architecture/security-foundations/using-example-terraform#organization-policy-setup

**Comment by ryotat7** [comment]
#37
