### ISSUE TITLE
Investigate using google_project_service_identity for bq email

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/terraform-google-log-analysis#5]
Using https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/project_service_identity maybe easier than using a data source to interpolate project num.

https://github.com/GoogleCloudPlatform/terraform-google-log-analysis/blob/2dc9c004c779c4c744cd8a8276b812ac620e1aca/main.tf#L151-L158

**Comment by ryotat7** [comment]
Replaced the block using google_project_service_identity
